inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Exclude:
    - 'test/unit/qrda/patient_round_trip_test.rb'
    - 'lib/qrda-import/patient_importer.rb'

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - 'lib/qrda-export/helper/date_helper.rb'

Metrics/ClassLength:
  Max: 110
  Exclude:
    - 'lib/qrda-import/base-importers/section_importer.rb'   
    - 'lib/qrda-import/patient_importer.rb' 
    - 'lib/qrda-export/catI-r5/qrda1_r5.rb'
    - 'lib/qrda-export/catIII-r2-1/qrda3_r21.rb'
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/unit/qrda/patient_round_trip_test.rb'
    - 'lib/qrda-import/patient_importer.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/qrda-import/patient_importer.rb'

Documentation:
  Enabled: false
Style/DateTime:
  Enabled: false
Performance/HashEachMethods:
  Enabled: false
