inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Documentation:
  Enabled: false
Style/DateTime:
  Enabled: false
Performance/HashEachMethods:
  Enabled: false
